# 2026-01-27 default GitHub Pages uses kramdown to generate HTML from .md files
#   problem is that naked https:// links are not clickable on output HTML
#   changing to "GFM" markdown to override default of kramdown 
#   NOTES do not render, see issue:
#   https://github.com/orgs/community/discussions/48797
#
markdown: GFM

# cut down GitHub CPU usage
exclude:
  - Mastodon/
  - Quotes_Pile/Reddit2025A/
  - Quotes_Pile/Reddit2025B/

include:
  - Quotes_Pile/Reddit2025A/Highlights/
  - Quotes_Pile/Reddit2025A/Censored/
  - Quotes_Pile/Reddit2025B/Highlights/
  - Quotes_Pile/Reddit2025A/Surkovian_Onion_Eating.md
  - Quotes_Pile/Reddit2026A/Censored/
